### ISSUE TITLE
Dosya sekmesine geçiş

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#1]
Ayarlar, Bulut veya Yardım sekmesi açık durumdayken, kullanıcı kod yazım alanına (scintilla) tıklarsa otomatik olarak Dosya sekmesine geçirebilir miyiz?

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin güncelledim Hocam.

**Comment by ttbilgin** [comment]
burada bir bug oluşmuş, video çekip mail attım.

**Comment by aysegul-hatipoglu** [comment]
çözüldü
