### ISSUE TITLE
Appjar Otomatik kurulum mesajı

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#10]
@aysegul-hatipoglu  bilgisayarda AppJar kurulu değilse otomatik algılayıp kurulum yaparken çıkan animasyondaki yazının bir kısmı kesilmiş , bunu düzeltelim.
![image](https://user-images.githubusercontent.com/854154/183290234-0cf4acf7-914b-4360-844d-c5e1b534bfe2.png)

**Comment by aysegul-hatipoglu** [comment]
Bende kesik değil @ttbilgin  hocam farklı ekran çözünürlüklerinde ve yakınlaştırma derecesini değişerek denedim. Sizde neden öyle bilemiyorum ama metnin yarısını alt satıra atarak düzelttim. Bu şekilde uygun olur mu?
![image](https://user-images.githubusercontent.com/13594146/183661091-a5b1dd8f-85a2-4c04-a747-db6267de8e43.png)

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu  teşekkürler, şimdi güzel olmuş
