### ISSUE TITLE
ActiveteWindow önerisi

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#11]
@aysegul-hatipoglu  ekteki videoyu izleyebilir misin?
[Untitled1.zip](https://github.com/ttbilgin/PyNar_Beta/files/9276949/Untitled1.zip)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin Ekledim hocam inceler misiniz?

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu 
Evet kodda hata var ise editörü ön plana çıkarıyor ama kodda hata yok ise de editörü ön plana çıkarıyor konsol hemen arkada kaldığı için hatasız kodlarda problme oluyor.

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu belki de hata listesine göre activate yapmak yerine hata.txt nin içi boş mu diye bakarak activate yapmak gerekecek. Yani kodda hata yok ise editörü ön plana actrivate yapmasın.

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin düzelttim hocam.

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu  teşekkürler olmuş.
