### ISSUE TITLE
ingilizce hata problemi

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#12]
@aysegul-hatipoglu  bizim test dosyalarında 30.py dosyasındaki hata ingilizcd olarak geliyor, bunun için hata tablosuna türkçe karşılık ekleyebilir misin?

![image](https://user-images.githubusercontent.com/854154/184410013-293f3bc1-ed81-4b46-abfe-20ef3f1080bf.png)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin ekledim hocam.

**Comment by ttbilgin** [comment]
Teşekkürler, olmuş
