### ISSUE TITLE
Debug Sistemi Çökmesi

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#13]
@aysegul-hatipoglu 
Pynar editörde yeni bir boş sekme açalım. sonra debug butonuna basalım. Karşımıza Kaydet penceresi geliyor. Bu pencereyi iptal diyerek kapatalım. bu durumda Pynar Çöküyor. Bir kontrol yapılması gerekli sanırım.

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin ekledim hocam.

**Comment by ttbilgin** [comment]
olmuş teşekkürler.
