### ISSUE TITLE
emoji paketi yeni versiyon bug

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#14]
@aysegul-hatipoglu  emoji paketinin yeni versiyonunda UNICODE_EMOJI kaldırılmış bu yüzden emoji 2.0 paketiyle pynar çalışmıyor.

![image](https://user-images.githubusercontent.com/854154/184429286-4b19b990-2148-4b59-af90-c7b62e09a189.png)

sitesinde bu durum belirtilmiş, bunu nasıl düzeltiriz? https://github.com/carpedm20/emoji/releases

**Comment by aysegul-hatipoglu** [comment]
Kontrol ettim hocam bazı değişken ve işlemler kaldırılmış ama çok fazla değil onları kod dosyasına ekleyerek emoji paketinden kullanmadığımda problem çözüldü. emoji paketinin farklı versiyonlarındada test ettim. Bu şekilde bir çözüm uygunmudur? @ttbilgin

**Comment by ttbilgin** [comment]
çalışıyor teşekkürler.
