### ISSUE TITLE
CustomizeDialog UI bug

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#15]
@aysegul-hatipoglu  bu diyalog penceresindeki ikon görünmüyor, bu hangi ikon olmalı? Bunu oluşturmak için bir python paketini kaldır o zaman göreceksin.

![image](https://user-images.githubusercontent.com/854154/189816449-2099247a-e782-4a1d-b355-8d5a8d3090ff.png)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin çözüldü hocam.
