### ISSUE TITLE
CustomizeUI bug

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#16]
İlk çalıştırmada AppJar yok ise "kur" dediğimizde ekrana gelen dialogda tema hatası var

![image](https://user-images.githubusercontent.com/854154/189818257-54d2a7f7-865e-4159-be6e-70325e28a7eb.png)

**Comment by aysegul-hatipoglu** [comment]
![image](https://user-images.githubusercontent.com/13594146/190242012-2a713823-9eb9-4249-9663-1f7b89f6473d.png)
Hocam mesajbox tasarımı değiştirilmeden önce böyleydi. Bura için tasarımda bir değişiklik eklenmemiş o yüzden bozulmuş şu şekilde düzenledim.
![image](https://user-images.githubusercontent.com/13594146/190248120-925f25fa-5c0b-46c0-b5d1-9efa4e0950e9.png)

@ttbilgin
