### ISSUE TITLE
Hakkında Penceresi başlığındaki help ikonunu silelim

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#17]
![image](https://user-images.githubusercontent.com/854154/189818609-0e457a4b-3128-4db0-8d63-455bb010dbdd.png)

**Comment by aysegul-hatipoglu** [comment]
Silindi minimize maximize ikonları ekledim @ttbilgin. 

![image](https://user-images.githubusercontent.com/13594146/190239371-6560ae2e-a6f2-4953-8c59-5e2dca22a20c.png)
