### ISSUE TITLE
IndicatorFill Bug

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#18]
@aysegul-hatipoglu  şu commit'te (https://github.com/ttbilgin/PyNar_Beta/commit/b18cd3b4140a961f5c3b925bdde8689a5654bf11#diff-3514e86ae021fc730d7eae932b512cfbe20e204f18a54c2f22a311a8612448a2) düzenlediğin onTextChanged() metodunda bir mantık hatası var bu yüzden self.indicatorFill()  satırı çalışmıyor ve bu yüzden tıklanabilir ipucu kelimeleri tıklanabilir şekilde olmuyor. 

ESKİSİ (çalışan)
![image](https://user-images.githubusercontent.com/854154/189824954-e55d0ca1-420b-482f-9cd6-3e6689cf5e47.png)

YENİSİ (Çalışmayan)
![image](https://user-images.githubusercontent.com/854154/189825068-0f39006b-9d61-42a4-bb46-3bba6975a097.png)

**Comment by ttbilgin** [comment]
bu şu an çalışıyor nedense, demekki benden kaynaklı bir problem olmuş.

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin düzeltildi.
