### ISSUE TITLE
CodeDataset'e kopyalamayı bırakalım

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#2]
Her bir başarılı çalışan kodun kod dataset içine kopyalanmasını iptal edelim. Hakan'ın çalıştığı yeni hata modelinde buna gerek kalmıyor. Ayrıca zaten pynar kurulum klasörünü gereksiz yere şişiriyordu.

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin Güncelledim Hocam.
