### ISSUE TITLE
Hatalı Font tür veya boyut seçimi için sıfırlama imkanı sunmak

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#3]
Bazı kullanıcılar uygun olmayan font tür veya boyutu seçtiklerinde ekrandaki metinler okunamaz olabiliyor. Bunun için bir tuş kombinasyonuna "pynar.ini" dosyasını varsayılan duruma döndürmek için bir event ekleyebilirmiyiz?

Mesela Ctrl+G tuşuna basınca pynar.ini içindeki aşağıdaki değerler öntanımlı değerler ile doldurulsun ve pynar editör restart etsin.
Ayarlarda Font ayarları penceresi açılırken de "Seçtiğiniz yazıtipi ayarları pynar editörü kullanışsız hale getirirse varsayılan ayarları yüklemek için herhangi bir anda Ctrl+G tuşuna basabilirsiniz." şeklinde bir mesaj kutusu görüntüleyelim.

[Font]
code_font = Consolas
editor_font = Tahoma
[Size]
size = 16
editorsize = 10

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin Güncelledim Hocam.

**Comment by ttbilgin** [comment]
Ayşegül Ctrl + G kısayolunu şu listeye de eklermisin?

![image](https://user-images.githubusercontent.com/854154/168490932-e29c4ec9-e4f5-4f31-b332-492b8332315f.png)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin ekledim Hocam.

**Comment by ttbilgin** [comment]
Şu uyarı "Toolbar' da ayarlar ikonunu tıklayınca geliyor.
![image](https://user-images.githubusercontent.com/854154/168543856-d8fe70f5-36c4-4dd2-b30e-46ce24c8c18e.png)

Uyarı, ayarlar penceresi geldikten sonra kullanıcı bir font seçmek için font adını tıkayınca gelmeli.

![image](https://user-images.githubusercontent.com/854154/168544034-21ee0fb7-f9b5-466a-9b01-22c2c82c9a87.png)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin dikkat etmemişim Hocam "Font ayarları penceresi açılırken" gelecek şekilde güncelledim
