### ISSUE TITLE
Hata Ayıklayıcı penceresinin Tema'sının genele uyarlanması

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#4]
Hata ayıklayıcı penceresinin tema'sı eski kalmış. Bul penceresi gibi yapalım.

![image](https://user-images.githubusercontent.com/854154/168324266-9b74223f-2c08-4f7f-8d82-5f8d588dd9fd.png)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin güncelledim Hocam.
