### ISSUE TITLE
Python Interpreter seçimi

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#5]
@aysegul-hatipoglu şimdi şu öneriyi gerçekleyeceğiz. https://github.com/ttbilgin/PyNar_Hata_Raporlama/issues/50

Bunun için Mustafa bilgisayardaki python sürümlerini algılayarak pynar.ini içine yazan bir kod yazdı (detectos.py içinde)
şu 3 dosyayı incele lütfen.
[16-05-2022-pythons-versions.zip](https://github.com/ttbilgin/PyNar_Beta/files/8698273/16-05-2022-pythons-versions.zip)

Şimdi artık pynar.ini içinde System bölümünde şu 4 direktif var.

[System]
system =
installed_pythons_versions = 
installed_pythons_exes = 
selected_python_version = 
selected_python_exe = 

Sende bilgisayarına en az 2 farklı python sürümü kur. (Kurarken Add To Path seçeneğini de seçmeyi unutma)
pynar.ini de bütün sürümleri algılıyormu test edelim. Eğer çalışıyorsa installed_pythons_versions ve installed_pythons_exes kullanarak Ayarlar bölümünde kullanıcıya bunlardan seçim yaptıracağız ve kullanıcının sonucunu selected_python_version ve selected_python_exe değişkenine yazdıracağız (bunun için get ve set metotları configuration.py içinde var)

Şöyle bir GUI tasarlayabilirsin

![image](https://user-images.githubusercontent.com/854154/168548370-91062843-1160-4144-9b6a-3b035a110444.png)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin güncelledim Hocam.

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu 
pynar.ini içindeki System bölümünde herşeyi boşalttım, pynarı tekrar başlattım. "automatic_selection" dışındaki herşeyi başarıyla doldurdu. Fakat bu boş kalan alan yüzünden pynar Ayarlar penceresi açılmıyor. Hata dökümü aşağıda

![image](https://user-images.githubusercontent.com/854154/169668425-9522e6d6-75d5-478e-b649-a3ea52401821.png)

**Comment by ttbilgin** [comment]
Ayarlardaki QCombobox'da hangi seçeneği seçersek seçelim, pynarı kapatıp açınca qcombobox'da hep ilk değer görünüyor. Bu durumda kullanıcı python sürümü değişmemiş gibi algılıyor. Python sürümü değiştiğinde Ayarlar penceresi tekrar açılırsa setCurrentIndex ile kullanıcının daha önce seçtiği seçenek default olarak gelsin. Eğer daha kolay olacaksa kullanıcının seçtiği seçeneğin indeksini de pynar.ini'de tutabilirsin.
Örnek: https://www.geeksforgeeks.org/pyqt5-setting-current-index-in-combobox/

![image](https://user-images.githubusercontent.com/854154/169669925-1776b899-362b-477a-83b5-84a2effb812f.png)

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu ekte zip olarak verilen dosyalarda ben değişiklik yaptım, böylece kodlar çalıştırılırken (run) ve interpreter açarken ve paket yöneticisini açarken kullanıcının seçtiği python sürümü ile çalışması sağlandı. Sen yine de iyice test et, belki gözümden kaçan bişey olmuştur. Ekteki dosyalardaki değişiklikleri winmerge ile gözlemlersin.
[22-05-2022.zip](https://github.com/ttbilgin/PyNar_Beta/files/8750262/22-05-2022.zip)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin Hocam değişiklikleri inceledim, birleştirdim test ettim ve güncelledim.

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu python interpreter seçerken "Ben seçeceğim" bölümünü işaretledikten sonra kaydettim pynar'ı kapattım. Sonra tekrar açtım "Otomatik Seç" yaptım kaydettim kapattım. Tekrar açtığımda "Ben seçeceğim" seçeneğinde en son ne seçmişsem o interpreter kalıyor. Halbuki herhangi bir zamanda kullanıcı "Otomatik seç" derse pynar.ini'deki şu alanları şöyle boşaltalım. Böylece pynar tekrar başlarken default değerler ile bunları tekrar doldurur.

[System]
system =
installed_pythons_versions =
installed_pythons_exes =
selected_python_version =
selected_python_exe = 
automatic_selection = True

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin güncelledim Hocam.
