### ISSUE TITLE
AutoCompleteList Ekleme için test

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#6]
@aysegul-hatipoglu pynar editöre kendimizin autocomplete kelimeleri ve hatta CallTip eklemesini sağlayacak birkaç modifikasyon yaptım bunu test edermisin? AutocompleteLists klasöründeki dosyaların yapısını incele, sende birkaç şey ekle bakalım beklendiği gibi çalışıyormu?

![image](https://user-images.githubusercontent.com/854154/170820190-4920bdb7-e007-4c21-858a-5a8c35b6daf4.png)

**Comment by ttbilgin** [comment]
değişen dosyalar şunlar
[28-05-2022.zip](https://github.com/ttbilgin/PyNar_Beta/files/8790913/28-05-2022.zip)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin Hocam test ettim iki işlemde gayet güzel çalışıyor. Değişiklikleri githubda güncelledim.
