### ISSUE TITLE
Debugger Özelliği Ekleme

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#7]
Debugger özelliği eklemek için birkaç iş yapacağız ama burada yapılan işleri commit etmeyelim, sadece değişen dosyaları bana mail at öyle test edeyim.

1) Python Yorumlayıcı Butonunun yanına bir tane böcek ikonu koyalım. İnternetten sen bizim genel temaya göre bişeyler ayarlarsın. https://www.google.com/search?q=debug+icon&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiOuqTc94H4AhW_SvEDHQeIBMcQ_AUoAXoECAEQAw&biw=1920&bih=909&dpr=1

2) Bu ikonu bağlayacağımız event için pynar.py içindeki "def interpreter(self)" fonksiyonunun aynısını yap adı "def debugger(self)" olsun. içeriği şimdilik interpreter ile aynı kalabilir.

Bunları bitirince daha sonraki adımları anlatırım.

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin Ekledim hocam. 

[29-05-2022.zip](https://github.com/ttbilgin/PyNar_Beta/files/8793346/29-05-2022.zip)

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu gayet güzel. Şimdi
pynar.py içindeki 
def debugger metodu içinde, codeeditor.py deki "self.breakpointLine" (satırlara koyduğumuz kırmızı ok işaretinin konumu) değişkeninin değerine nasıl erişiriz? debugger içinde bu kırmızı ok işaretinin konumunu konsola print edermisin?

![image](https://user-images.githubusercontent.com/854154/170894110-68ea9663-8991-41f9-bfbb-1ffe3d6630b7.png)

**Comment by aysegul-hatipoglu** [comment]
![image](https://user-images.githubusercontent.com/13594146/171380310-7ea00dc6-7c45-4b90-8bb3-6450217bc0be.png)

@ttbilgin şu şekilde ulaşıp konsola basabiliyorum hocam

**Comment by aysegul-hatipoglu** [comment]
![image](https://user-images.githubusercontent.com/13594146/171380410-5c5217a1-1eda-43d8-aa43-3c149c8a3b48.png)
@ttbilgin şu şekilde ulaşıp konsola basabiliyorum hocam.

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu  Bu değişiklik için dosyalar nerde? Dosya yüklemişmiydin? ben ulaşamadım.

**Comment by aysegul-hatipoglu** [comment]
Sadece bir print olduğundan dosya yüklemedim hocam3 Haz 2022 00:42 tarihinde ttbilgin ***@***.***> yazdı:

@aysegul-hatipoglu  Bu değişiklik için dosyalar nerde? Dosya yüklemişmiydin? ben ulaşamadım.

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu  işte o kodu yaz buraya ozaman :) print ile neyi yazdırdın?  def debugger fonksiyonunu buraya yapıştırabilirsin. Ben senin ekran görüntündeki çıktıyı nasıl elde edeceğim o kodlar lazım bana.

**Comment by aysegul-hatipoglu** [comment]
Işaretli satırın kodunu yazdırdım :) k.bakmayin tüm gün disardaydım mailinize telefondan cevap verdim. Eve geçince atarım hemen kodu.3 Haz 2022 17:19 tarihinde ttbilgin ***@***.***> yazdı:

@aysegul-hatipoglu  işte o kodu yaz buraya ozaman :) print ile neyi yazdırdın?  def debugger fonksiyonunu buraya yapıştırabilirsin. Ben senin ekran görüntündeki çıktıyı nasıl elde edeceğim o kodlar lazım bana.

**Comment by aysegul-hatipoglu** [comment]
[pynar.zip](https://github.com/ttbilgin/PyNar_Beta/files/8835095/pynar.zip)

@ttbilgin  Hocam son değişiklillerin üzerine sadece pynar.py yi güncelleyerek son eklediğim kodları test edebilirsiniz

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu  Debugger için senin yazdığın metodun içini işaretçinin gösterdiği yere kadar çalıştıracak şekilde düzenledim. sonrasında devam etmek için enter tuşuna basarak satır satır devam edilebiliyor.  Bu kodu çeşitli örneklerde test edebilir misin? Eğer sorun yok ise commit edbilirsin. Değişen dosya sadece pynar.py
[pynar_debugger_4haz2022.zip](https://github.com/ttbilgin/PyNar_Beta/files/8837686/pynar_debugger_4haz2022.zip)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin güncelledim hocam.
