### ISSUE TITLE
breakpoint bug

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#8]
@aysegul-hatipoglu Sol menüden sürüklediğimiz kodlara breakpoint (kırmızı ok) neden koyamıyoruz?

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin kontrol ettim breapoint koyabiliyorum ben hocam.
[break-point.zip](https://github.com/ttbilgin/PyNar_Beta/files/8839235/break-point.zip)

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu  evet haklısın şimdi temiz bir sürüm indirip denedim, benden kaynaklı bişey olmuş sanırım. kapatıyorum bu issue'yı.
