### ISSUE TITLE
Linux UI iyileştirme

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_Beta#9]
Pardusta Şurada bir tasarım problemi var 
![image](https://user-images.githubusercontent.com/854154/172242877-52969df4-2fd5-4b58-9a50-ca992e835ec5.png)

Ayrıca kısayollar butonunda da CSS problemi var
![image](https://user-images.githubusercontent.com/854154/172243007-42e2fb9b-ace2-4217-9f0c-4453145b13fc.png)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin Düzelttim Hocam.
